version: '3.4'

services:
    app:
        build: .
        entrypoint: [ "/entrypoint.sh" ]
        volumes:
            - maven_cache:/root/.m2
            - npm_cache:/root/.npm
            - node_modules_cache:/workspace/frontend/src/main/frontend/node/node_modules
        ports:
            - 8080:8080
            - 4200:4200
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: delldell
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - 3306:3306
    duing:
        image: kairops/duing
        ports:
          - 3389:3389
        shm_size: 1g
        privileged: true
        volumes:
            - ./test/features:/opt/duingdemo/ci-scripts/test/cucumber/features
            - ./test/reports:/opt/duingdemo/ci-scripts/test/cucumber/reports
volumes:
    dbdata:
    maven_cache:
    node_modules_cache:
    npm_cache: